### ISSUE TITLE
Incompatible with asn1crypto >= 1.0.0

### ISSUE THREAD

**Issue by krizex** [skelsec/minikerberos#10]
When executing the `examples/getTGT.py`, we will get the following error:
```
DEBUG:root:Getting TGT
Traceback (most recent call last):
  File "minikerberos/minikerberos/examples/getTGT.py", line 42, in <module>
    main()
  File "minikerberos/minikerberos/examples/getTGT.py", line 36, in main
    kc.get_TGT()
  File "/usr/local/lib/python3.6/dist-packages/minikerberos/communication.py", line 250, in get_TGT
    kdc_req['req-body'] = KDC_REQ_BODY(kdc_req_body)
  File "/usr/local/lib/python3.6/dist-packages/asn1crypto/core.py", line 3408, in __init__
    raise e
  File "/usr/local/lib/python3.6/dist-packages/asn1crypto/core.py", line 3392, in __init__
    self.__setitem__(key, value[key])
  File "/usr/local/lib/python3.6/dist-packages/asn1crypto/core.py", line 3548, in __setitem__
    new_value = self._make_value(field_name, field_spec, value_spec, field_params, value)
  File "/usr/local/lib/python3.6/dist-packages/asn1crypto/core.py", line 3803, in _make_value
    new_value = value_spec(value, **field_params)
  File "/usr/local/lib/python3.6/dist-packages/asn1crypto/core.py", line 1677, in __init__
    raise e
  File "/usr/local/lib/python3.6/dist-packages/asn1crypto/core.py", line 1669, in __init__
    self.set(value)
  File "/usr/local/lib/python3.6/dist-packages/asn1crypto/core.py", line 5083, in set
    raise ValueError('Must be timezone aware')
ValueError: Must be timezone aware
    while constructing minikerberos.asn1_structs.KerberosTime
    while constructing minikerberos.asn1_structs.KDC_REQ_BODY
```

But it is fine to work with asn1crypto==0.24.0
The change of asn1crypto was introduced in https://github.com/wbond/asn1crypto/commit/c21f024f3834e1f1c00d92daccd71ded31505cc2

**Comment by skelsec** [comment]
I'm working on updating to the latest asn1crypto version. But first, I'm waiting to resolve 
https://github.com/skelsec/minikerberos/pull/9

**Comment by skelsec** [comment]
The code has been updated, now it should be working with asn1crypto>=1.3.0

**Comment by krizex** [comment]
The latest master branch works for asn1crypto1.3.0 now. 
Please release it to pypi also. Thanks!
